[project]
name = "hierarchical-brain-atlas"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "antspyx>=0.5.4",
    "datalad-osf>=0.3.0",
    "jupyterlab>=4.4.1",
    "nibabel>=5.3.2",
    "ruff>=0.11.6",
]
